# Generated by Django 3.1.3 on 2021-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakeid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='cake/images')),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('eggless', models.BooleanField()),
                ('ingredients', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=70)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
