# Generated by Django 3.1.3 on 2021-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakeapi', '0004_auto_20210424_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('cakeid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='cake/images')),
                ('price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('eggless', models.BooleanField()),
                ('ingredients', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=70)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
