# Generated by Django 3.1.3 on 2021-04-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapi', '0007_auto_20210426_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cakes', models.ManyToManyField(blank=True, to='cakeapi.Cake')),
            ],
        ),
    ]
