# Generated by Django 3.1.3 on 2021-04-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapi', '0009_auto_20210427_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
