# Generated by Django 3.1.3 on 2021-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapi', '0010_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorder',
            name='cakes',
            field=models.ManyToManyField(blank=True, to='cakeapi.Carts'),
        ),
    ]
