# Generated by Django 3.1.3 on 2021-04-29 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapi', '0011_auto_20210428_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutFinal',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cakes', models.ManyToManyField(blank=True, to='cakeapi.Carts')),
            ],
        ),
    ]
