# Generated by Django 3.1.3 on 2021-04-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapi', '0003_auto_20210423_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Cakes',
        ),
    ]
