# Generated by Django 3.1.3 on 2021-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapi', '0008_addorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorder',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
